#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VideoBuyApp.Resource", IsApplication=true)]

namespace VideoBuyApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int black_bg1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int video_thumbnail_default1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int video_thumbnail_default2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int wood_bg1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int wood_bg2 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int MassageField = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int MassageTechnicField = 2131165194;
			
			// aapt resource value: 0x7f070016
			public const int UiPreviewAndBuyButton = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int UiVideoIcon = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int UiVideoPrice = 2131165192;
			
			// aapt resource value: 0x7f070015
			public const int UiVideoTitle = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int UiVideoTitleBuy = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int UiVideosList = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int VideoTiming = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int bBuy = 2131165202;
			
			// aapt resource value: 0x7f070001
			public const int bLogIn = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int bSetAsRingtone = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int bSignUp = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int editText1 = 2131165184;
			
			// aapt resource value: 0x7f070013
			public const int imageView1 = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int incomingVideo = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int radioButtonEmail = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int radioButtonSMS = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int radioGroup1 = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int scrollView1 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int textView1 = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int videoPlayer = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int videocontainer = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AcountLogIn = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AcountVideoList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AcountVideoPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FinalDialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IncomingCall = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Preview_Buy = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int VideoListItem = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int test = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
